name: AppLink

on:
  push:
    branches:
      - 'main'

jobs:

  applink-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: vendor/bin/phpunit

  applink-docker-build:
    runs-on: ubuntu-24.04
    needs: applink-test
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: stefanhuber332/applink:latest
