name: AppLink

on:
  push:
    branches:
      - 'main'

jobs:

  applink-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: vendor/bin/phpunit
